// Physics collider overlay: what the simulation is actually colliding with.
//
// Everything else about a body is authored (PhysicsConfig in userData) and
// therefore visible in the inspector — but the SHAPE that authoring resolves to
// is not, and a body resting on nothing is indistinguishable from a body whose
// collider is somewhere else entirely. PhysX draws its own colliders into a
// per-scene line buffer; this turns that buffer into one LineSegments under the
// editor overlay, so the answer is in the viewport.
//
// The buffer is regenerated by every simulate() and changes length as bodies
// come and go, which makes it exactly the case SplineOverlay::writeSamples was
// written for: the renderer caches GPU buffers by ATTRIBUTE IDENTITY, so a
// fresh attribute every frame can hand it a recycled pointer that reads as
// already uploaded and the overlay freezes. The attribute is rewritten in
// place, replaced only when the buffer outgrows it, and the orphaned geometry
// is disposed when it is.
//
// Visualization is not free — PhysX builds the buffer during simulate() — so
// the eSCALE parameter is switched off rather than merely ignored when the view
// is off.

#include "EditorApp.hpp"
#include "EditorTheme.hpp"

#ifdef THREEPP_EDITOR_WITH_PHYSX
#include "threepp/extras/editor/PhysicsPlaySession.hpp"
#endif

#include "threepp/core/BufferGeometry.hpp"
#include "threepp/materials/LineBasicMaterial.hpp"
#include "threepp/objects/LineSegments.hpp"

#include <imgui.h>// theme colours are ImVec4

using namespace threepp;
using namespace threepp::editor;

namespace {

    // Over scene geometry, under the marker icons — the same band the spline
    // curves are drawn in.
    constexpr int kColliderRenderOrder = 3000;

}// namespace


void EditorApp::syncPhysicsDebug() {

#ifdef THREEPP_EDITOR_WITH_PHYSX

    using namespace ::physx;

    // world() is null between plays: the session destroys it in stop().
    auto* world = physics_ ? physics_->world() : nullptr;

    if (!world || !physicsDebug_) {
        if (world) {
            world->scene().setVisualizationParameter(PxVisualizationParameter::eSCALE, 0.f);
        }
        clearPhysicsDebug();
        return;
    }

    auto& scene = world->scene();
    scene.setVisualizationParameter(PxVisualizationParameter::eSCALE, 1.f);
    scene.setVisualizationParameter(PxVisualizationParameter::eCOLLISION_SHAPES, 1.f);

    // Filled by simulate(); a frame that ran no substep keeps the last one,
    // which is what the toggle wants (the lines do not blink at low dt).
    const PxRenderBuffer& buffer = scene.getRenderBuffer();
    const auto lineCount = static_cast<int>(buffer.getNbLines());
    const int vertices = lineCount * 2;

    if (!physicsDebugLines_) {
        auto material = LineBasicMaterial::create(LineBasicMaterial::Params()
                                                          .color(Color(0xffffff))
                                                          .toneMapped(false));
        const auto tint = theme::accent();
        // One colour for the lot. PhysX tags each line with a shape-state
        // colour, which says less here than "this is the collider" does.
        material->color.setRGB(tint.x, tint.y, tint.z);
        physicsDebugLines_ = LineSegments::create(BufferGeometry::create(), material);
        physicsDebugLines_->renderOrder = kColliderRenderOrder;
        // In-place updates never refresh cached bounds, and PhysX hands out
        // world-space lines that must not vanish at the edges of a stale one.
        physicsDebugLines_->frustumCulled = false;
        physicsDebugLines_->matrixAutoUpdate = false;
        physicsDebugCapacity_ = 0;
        overlay_->add(physicsDebugLines_);
    }

    if (vertices > physicsDebugCapacity_) {
        const auto old = physicsDebugLines_->geometry();
        auto geometry = BufferGeometry::create();
        geometry->setAttribute("position", FloatBufferAttribute::create(
                                                   std::vector<float>(vertices * 3), 3));
        physicsDebugLines_->setGeometry(geometry);
        if (old) old->dispose();
        physicsDebugCapacity_ = vertices;
    }

    auto* position = physicsDebugLines_->geometry()->getAttribute<float>("position");
    if (!position) {
        physicsDebugLines_->visible = false;
        return;
    }
    if (vertices == 0) {
        // PhysX REFILLS the buffer on each simulate(), so a frame that ran no
        // substep finds it empty rather than unchanged. Keep the last lines —
        // which is what the note above promises — instead of hiding the overlay
        // and blinking it at every frame the accumulator swallows.
        physicsDebugLines_->visible = physicsDebugLines_->geometry()->drawRange.count > 0;
        return;
    }
    physicsDebugLines_->visible = true;

    const PxDebugLine* lines = buffer.getLines();
    for (int i = 0; i < lineCount; ++i) {
        position->setXYZ(i * 2, lines[i].pos0.x, lines[i].pos0.y, lines[i].pos0.z);
        position->setXYZ(i * 2 + 1, lines[i].pos1.x, lines[i].pos1.y, lines[i].pos1.z);
    }
    position->needsUpdate();
    // The tail beyond `vertices` still holds whatever a busier frame left there.
    physicsDebugLines_->geometry()->drawRange = {0, vertices};

#else
    clearPhysicsDebug();
#endif
}

void EditorApp::clearPhysicsDebug() {

    if (!physicsDebugLines_) return;

    physicsDebugLines_->removeFromParent();
    // The renderer keys GPU buffers on geometry identity; an orphan that is
    // never disposed both leaks them and re-arms the recycled-pointer
    // staleness the in-place write above exists to avoid.
    if (const auto geometry = physicsDebugLines_->geometry()) geometry->dispose();
    physicsDebugLines_.reset();
    physicsDebugCapacity_ = 0;
}
