// Physics debug overlay: what the simulation is actually doing.
//
// Everything else about a body is authored (PhysicsConfig in userData) and
// therefore visible in the inspector — but the SHAPE that authoring resolves to
// is not, and a body resting on nothing is indistinguishable from a body whose
// collider is somewhere else entirely. The same goes for a JOINT: the authored
// axis helper is hidden with the rest of the authoring layer during Play, and
// the constraint the solver actually enforces (its live frames, its limits, its
// absence once it breaks) is knowable only from here. PhysX draws both into a
// per-scene line buffer; this turns that buffer into one LineSegments under the
// editor overlay, so the answer is in the viewport.
//
// The buffer is regenerated by every simulate() and changes length as bodies
// come and go, which makes it exactly the case SplineOverlay::writeSamples was
// written for: the renderer caches GPU buffers by ATTRIBUTE IDENTITY, so a
// fresh attribute every frame can hand it a recycled pointer that reads as
// already uploaded and the overlay freezes. The attribute is rewritten in
// place, replaced only when the buffer outgrows it, and the orphaned geometry
// is disposed when it is.
//
// Visualization is not free — PhysX builds the buffer during simulate() — so
// the eSCALE parameter is switched off rather than merely ignored when the view
// is off.

#include "EditorApp.hpp"

#ifdef THREEPP_EDITOR_WITH_PHYSX
#include "threepp/extras/editor/PhysicsPlaySession.hpp"
#endif

#include "threepp/core/BufferGeometry.hpp"
#include "threepp/materials/LineBasicMaterial.hpp"
#include "threepp/objects/LineSegments.hpp"

using namespace threepp;
using namespace threepp::editor;

namespace {

    // Over scene geometry, under the marker icons — the same band the spline
    // curves are drawn in.
    constexpr int kColliderRenderOrder = 3000;

}// namespace


void EditorApp::syncPhysicsDebug() {

#ifdef THREEPP_EDITOR_WITH_PHYSX

    using namespace ::physx;

    // world() is null between plays: the session destroys it in stop().
    auto* world = physics_ ? physics_->world() : nullptr;

    if (!world || !physicsDebug_) {
        if (world) {
            world->scene().setVisualizationParameter(PxVisualizationParameter::eSCALE, 0.f);
        }
        clearPhysicsDebug();
        return;
    }

    auto& scene = world->scene();
    scene.setVisualizationParameter(PxVisualizationParameter::eSCALE, 1.f);
    scene.setVisualizationParameter(PxVisualizationParameter::eCOLLISION_SHAPES, 1.f);
    // Joints too: the local frames say where each constraint actually acts and
    // the limits say what it allows — the live counterpart of the authored
    // axis helper, which Play hides with the rest of the authoring layer. A
    // broken joint stops being drawn, which is exactly the news. Only joints
    // carrying PxConstraintFlag::eVISUALIZATION appear; the Joint wrapper
    // raises it on every one it creates.
    scene.setVisualizationParameter(PxVisualizationParameter::eJOINT_LOCAL_FRAMES, 1.f);
    scene.setVisualizationParameter(PxVisualizationParameter::eJOINT_LIMITS, 1.f);

    // Filled by simulate(); a frame that ran no substep keeps the last one,
    // which is what the toggle wants (the lines do not blink at low dt).
    const PxRenderBuffer& buffer = scene.getRenderBuffer();
    const auto lineCount = static_cast<int>(buffer.getNbLines());
    const int vertices = lineCount * 2;

    if (!physicsDebugLines_) {
        // PhysX's own per-line colours, not one flat tint. That was the right
        // call when the buffer held only colliders — "this is the collider"
        // was the whole message — but the joints draw into the same buffer,
        // and their colour IS their meaning: RGB triads for the local frames,
        // the limit arcs in their own colours. Flattening that would erase
        // exactly what the joint lines add.
        auto material = LineBasicMaterial::create(LineBasicMaterial::Params()
                                                          .vertexColors(true)
                                                          .toneMapped(false));
        physicsDebugLines_ = LineSegments::create(BufferGeometry::create(), material);
        physicsDebugLines_->renderOrder = kColliderRenderOrder;
        // In-place updates never refresh cached bounds, and PhysX hands out
        // world-space lines that must not vanish at the edges of a stale one.
        physicsDebugLines_->frustumCulled = false;
        physicsDebugLines_->matrixAutoUpdate = false;
        physicsDebugCapacity_ = 0;
        overlay_->add(physicsDebugLines_);
    }

    if (vertices > physicsDebugCapacity_) {
        const auto old = physicsDebugLines_->geometry();
        auto geometry = BufferGeometry::create();
        geometry->setAttribute("position", FloatBufferAttribute::create(
                                                   std::vector<float>(vertices * 3), 3));
        geometry->setAttribute("color", FloatBufferAttribute::create(
                                                std::vector<float>(vertices * 3), 3));
        physicsDebugLines_->setGeometry(geometry);
        if (old) old->dispose();
        physicsDebugCapacity_ = vertices;
    }

    auto* position = physicsDebugLines_->geometry()->getAttribute<float>("position");
    auto* color = physicsDebugLines_->geometry()->getAttribute<float>("color");
    if (!position || !color) {
        physicsDebugLines_->visible = false;
        return;
    }
    if (vertices == 0) {
        // PhysX REFILLS the buffer on each simulate(), so a frame that ran no
        // substep finds it empty rather than unchanged. Keep the last lines —
        // which is what the note above promises — instead of hiding the overlay
        // and blinking it at every frame the accumulator swallows.
        physicsDebugLines_->visible = physicsDebugLines_->geometry()->drawRange.count > 0;
        return;
    }
    physicsDebugLines_->visible = true;

    const PxDebugLine* lines = buffer.getLines();
    // PxDebugLine colours are 0xAARRGGBB words, one per endpoint.
    const auto writeColor = [color](int vertex, PxU32 argb) {
        color->setXYZ(vertex,
                      static_cast<float>((argb >> 16) & 0xffu) / 255.f,
                      static_cast<float>((argb >> 8) & 0xffu) / 255.f,
                      static_cast<float>(argb & 0xffu) / 255.f);
    };
    for (int i = 0; i < lineCount; ++i) {
        position->setXYZ(i * 2, lines[i].pos0.x, lines[i].pos0.y, lines[i].pos0.z);
        position->setXYZ(i * 2 + 1, lines[i].pos1.x, lines[i].pos1.y, lines[i].pos1.z);
        writeColor(i * 2, lines[i].color0);
        writeColor(i * 2 + 1, lines[i].color1);
    }
    position->needsUpdate();
    color->needsUpdate();
    // The tail beyond `vertices` still holds whatever a busier frame left there.
    physicsDebugLines_->geometry()->drawRange = {0, vertices};

#else
    clearPhysicsDebug();
#endif
}

void EditorApp::clearPhysicsDebug() {

    if (!physicsDebugLines_) return;

    physicsDebugLines_->removeFromParent();
    // The renderer keys GPU buffers on geometry identity; an orphan that is
    // never disposed both leaks them and re-arms the recycled-pointer
    // staleness the in-place write above exists to avoid.
    if (const auto geometry = physicsDebugLines_->geometry()) geometry->dispose();
    physicsDebugLines_.reset();
    physicsDebugCapacity_ = 0;
}
