#include "threepp/renderers/common/BC7Encode.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <thread>

namespace threepp::bcn {

namespace {

    // 4-bit BC7 interpolation weights (x/64) — MUST match BCnDecode.cpp's w4
    // table; the encoder chooses indices assuming exactly this palette.
    constexpr int kW4[16] = {0, 4, 9, 13, 17, 21, 26, 30, 34, 38, 43, 47, 51, 55, 60, 64};

    struct Block {
        // 16 texels RGBA, row-major within the block.
        std::uint8_t px[16][4];
    };

    // Gather one 4x4 block at (bx, by), clamping reads to the image border so
    // partial edge blocks repeat the border texel instead of pulling zeros
    // (zeros would drag the endpoint line toward black and ring the edge).
    void gatherBlock(const std::uint8_t* rgba, int w, int h, int bx, int by, Block& b) {
        for (int ty = 0; ty < 4; ++ty) {
            const int y = std::min(by * 4 + ty, h - 1);
            for (int tx = 0; tx < 4; ++tx) {
                const int x = std::min(bx * 4 + tx, w - 1);
                const std::uint8_t* s = rgba + (static_cast<size_t>(y) * w + x) * 4;
                std::uint8_t* d = b.px[ty * 4 + tx];
                d[0] = s[0];
                d[1] = s[1];
                d[2] = s[2];
                d[3] = s[3];
            }
        }
    }

    // Quantize a [0,255] float channel to a mode-6 endpoint: 7 explicit bits
    // plus a shared P-bit, reconstructing as (e7 << 1 | p) << 0 ... i.e. the
    // 8-bit endpoint is (e7:p). For a given p, the closest e7 to v is
    // round((v - p) / 2), clamped to [0,127].
    inline int quantize7(float v, int p) {
        const int q = static_cast<int>(std::lround((v - static_cast<float>(p)) * 0.5f));
        return std::clamp(q, 0, 127);
    }

    inline int reconstruct(int e7, int p) { return (e7 << 1) | p; }

    // Squared error of the block against the palette generated by endpoints
    // e0/e1 (8-bit reconstructed), writing the best index per texel.
    //
    // Index selection is projection-guided: project the texel onto the
    // endpoint segment, seed at the proportional palette entry, and test a
    // ±1 window (the kW4 spacing is near-linear, so the true optimum is
    // always inside it). 3 candidate evaluations per texel instead of 16 —
    // this is the encoder's hot loop, and Bistro-scale transcoding runs it
    // a few hundred million times.
    std::uint64_t assignIndices(const Block& b, const int e0[4], const int e1[4], int idx[16]) {
        int pal[16][4];
        for (int i = 0; i < 16; ++i) {
            for (int c = 0; c < 4; ++c) {
                pal[i][c] = (e0[c] * (64 - kW4[i]) + e1[c] * kW4[i] + 32) >> 6;
            }
        }
        float dir[4];
        float len2 = 0.f;
        for (int c = 0; c < 4; ++c) {
            dir[c] = static_cast<float>(e1[c] - e0[c]);
            len2 += dir[c] * dir[c];
        }
        const float invLen2 = len2 > 1e-6f ? 1.f / len2 : 0.f;

        std::uint64_t total = 0;
        for (int t = 0; t < 16; ++t) {
            float proj = 0.f;
            for (int c = 0; c < 4; ++c) {
                proj += (b.px[t][c] - e0[c]) * dir[c];
            }
            const int seed = std::clamp(static_cast<int>(proj * invLen2 * 15.f + 0.5f), 0, 15);
            const int lo = std::max(0, seed - 1);
            const int hi = std::min(15, seed + 1);
            int best = seed;
            std::uint64_t bestErr = ~0ull;
            for (int i = lo; i <= hi; ++i) {
                std::int64_t err = 0;
                for (int c = 0; c < 4; ++c) {
                    const int d = pal[i][c] - b.px[t][c];
                    err += static_cast<std::int64_t>(d) * d;
                }
                if (static_cast<std::uint64_t>(err) < bestErr) {
                    bestErr = static_cast<std::uint64_t>(err);
                    best = i;
                }
            }
            idx[t] = best;
            total += bestErr;
        }
        return total;
    }

    // Least-squares endpoint refinement for fixed indices: each texel is a
    // linear blend p = (1-w)*e0 + w*e1, so per channel the optimal endpoints
    // solve a 2x2 normal-equation system in (e0, e1).
    void refineEndpoints(const Block& b, const int idx[16], float e0[4], float e1[4]) {
        float a00 = 0.f, a01 = 0.f, a11 = 0.f;
        float bx0[4] = {0, 0, 0, 0}, bx1[4] = {0, 0, 0, 0};
        for (int t = 0; t < 16; ++t) {
            const float wgt = static_cast<float>(kW4[idx[t]]) / 64.f;
            const float u = 1.f - wgt;
            a00 += u * u;
            a01 += u * wgt;
            a11 += wgt * wgt;
            for (int c = 0; c < 4; ++c) {
                bx0[c] += u * b.px[t][c];
                bx1[c] += wgt * b.px[t][c];
            }
        }
        const float det = a00 * a11 - a01 * a01;
        if (std::fabs(det) < 1e-6f) return;// all texels on one palette entry — keep current
        const float inv = 1.f / det;
        for (int c = 0; c < 4; ++c) {
            const float n0 = (a11 * bx0[c] - a01 * bx1[c]) * inv;
            const float n1 = (a00 * bx1[c] - a01 * bx0[c]) * inv;
            e0[c] = std::clamp(n0, 0.f, 255.f);
            e1[c] = std::clamp(n1, 0.f, 255.f);
        }
    }

    // Append `n` low bits of `v` to the 128-bit block at bit cursor `pos`.
    inline void putBits(std::uint8_t* blk, int& pos, std::uint32_t v, int n) {
        for (int i = 0; i < n; ++i) {
            if ((v >> i) & 1u) blk[(pos + i) >> 3] |= static_cast<std::uint8_t>(1u << ((pos + i) & 7));
        }
        pos += n;
    }

    void encodeBlock(const Block& b, std::uint8_t out[16]) {
        // Initial endpoints: principal-axis extremes. Compute the RGBA mean,
        // then the dominant direction via a few power iterations on the
        // covariance — cheap and robust enough for 16 samples; the
        // least-squares refinement below does the fine work.
        float mean[4] = {0, 0, 0, 0};
        for (int t = 0; t < 16; ++t) {
            for (int c = 0; c < 4; ++c) mean[c] += b.px[t][c];
        }
        for (float& m : mean) m *= 1.f / 16.f;

        float cov[4][4] = {};
        for (int t = 0; t < 16; ++t) {
            float d[4];
            for (int c = 0; c < 4; ++c) d[c] = b.px[t][c] - mean[c];
            for (int r = 0; r < 4; ++r) {
                for (int c = 0; c < 4; ++c) cov[r][c] += d[r] * d[c];
            }
        }
        float axis[4] = {1.f, 1.f, 1.f, 1.f};
        for (int it = 0; it < 4; ++it) {
            float nx[4] = {0, 0, 0, 0};
            for (int r = 0; r < 4; ++r) {
                for (int c = 0; c < 4; ++c) nx[r] += cov[r][c] * axis[c];
            }
            float len = std::sqrt(nx[0] * nx[0] + nx[1] * nx[1] + nx[2] * nx[2] + nx[3] * nx[3]);
            if (len < 1e-6f) break;// flat block — axis irrelevant
            for (int c = 0; c < 4; ++c) axis[c] = nx[c] / len;
        }

        float tMin = 1e30f, tMax = -1e30f;
        for (int t = 0; t < 16; ++t) {
            float proj = 0.f;
            for (int c = 0; c < 4; ++c) proj += (b.px[t][c] - mean[c]) * axis[c];
            tMin = std::min(tMin, proj);
            tMax = std::max(tMax, proj);
        }
        float fe0[4], fe1[4];
        for (int c = 0; c < 4; ++c) {
            fe0[c] = std::clamp(mean[c] + tMin * axis[c], 0.f, 255.f);
            fe1[c] = std::clamp(mean[c] + tMax * axis[c], 0.f, 255.f);
        }

        // quantize -> index -> least-squares refine -> quantize -> index.
        // P-bits: only the matched pairs (0,0) and (1,1) are tried — they
        // cover the even/odd endpoint parity that matters; the mixed combos
        // buy a fraction of a code on rare blocks at double the encode cost.
        int bestIdx[16];
        int bestE0q[4], bestE1q[4];
        int bestP0 = 0, bestP1 = 0;
        std::uint64_t bestErr = ~0ull;

        for (int round = 0; round < 2; ++round) {
            for (int p = 0; p <= 1; ++p) {
                int e0q[4], e1q[4], e0r[4], e1r[4], idx[16];
                for (int c = 0; c < 4; ++c) {
                    e0q[c] = quantize7(fe0[c], p);
                    e1q[c] = quantize7(fe1[c], p);
                    e0r[c] = reconstruct(e0q[c], p);
                    e1r[c] = reconstruct(e1q[c], p);
                }
                const std::uint64_t err = assignIndices(b, e0r, e1r, idx);
                if (err < bestErr) {
                    bestErr = err;
                    bestP0 = p;
                    bestP1 = p;
                    std::memcpy(bestIdx, idx, sizeof(idx));
                    std::memcpy(bestE0q, e0q, sizeof(e0q));
                    std::memcpy(bestE1q, e1q, sizeof(e1q));
                }
            }
            if (bestErr == 0 || round == 1) break;
            refineEndpoints(b, bestIdx, fe0, fe1);
        }

        // Anchor constraint: index 0's MSB must be 0 (it isn't stored). If the
        // winning assignment gives texel 0 an index > 7, swap the endpoints and
        // invert every index — an exactly equivalent palette.
        if (bestIdx[0] > 7) {
            std::swap(bestE0q, bestE1q);
            std::swap(bestP0, bestP1);
            for (int& i : bestIdx) i = 15 - i;
        }

        // Pack mode 6: [0..6] mode marker (bit 6 set), 4x2 7-bit endpoint
        // channel pairs (R0 R1 G0 G1 B0 B1 A0 A1), P0, P1, then 63 index bits
        // (texel 0 stores 3 bits, the rest 4).
        std::memset(out, 0, 16);
        int pos = 0;
        putBits(out, pos, 1u << 6, 7);
        for (int c = 0; c < 4; ++c) {
            putBits(out, pos, static_cast<std::uint32_t>(bestE0q[c]), 7);
            putBits(out, pos, static_cast<std::uint32_t>(bestE1q[c]), 7);
        }
        putBits(out, pos, static_cast<std::uint32_t>(bestP0), 1);
        putBits(out, pos, static_cast<std::uint32_t>(bestP1), 1);
        putBits(out, pos, static_cast<std::uint32_t>(bestIdx[0]), 3);
        for (int t = 1; t < 16; ++t) {
            putBits(out, pos, static_cast<std::uint32_t>(bestIdx[t]), 4);
        }
    }

    // sRGB <-> linear lookup tables for the mip filter. Decode is exact per
    // 8-bit code; encode inverts through a 4096-entry table (about 1/16 of an
    // 8-bit step of quantization error — invisible two mip levels down).
    struct SrgbTables {
        std::array<float, 256> toLinear{};
        std::array<std::uint8_t, 4096> toSrgb{};
        SrgbTables() {
            for (int i = 0; i < 256; ++i) {
                const float s = i / 255.f;
                toLinear[i] = (s <= 0.04045f) ? s / 12.92f
                                              : std::pow((s + 0.055f) / 1.055f, 2.4f);
            }
            for (int i = 0; i < 4096; ++i) {
                const float lin = (i + 0.5f) / 4096.f;
                const float s = (lin <= 0.0031308f) ? lin * 12.92f
                                                    : 1.055f * std::pow(lin, 1.f / 2.4f) - 0.055f;
                toSrgb[i] = static_cast<std::uint8_t>(std::clamp(s * 255.f + 0.5f, 0.f, 255.f));
            }
        }
    };

}// namespace

std::vector<std::uint8_t> bc7EncodeMode6(const std::uint8_t* rgba, int w, int h) {

    const int bw = (w + 3) / 4;
    const int bh = (h + 3) / 4;
    std::vector<std::uint8_t> out(static_cast<size_t>(bw) * bh * 16);

    auto encodeRows = [&](int y0, int y1) {
        Block b;
        for (int by = y0; by < y1; ++by) {
            for (int bx = 0; bx < bw; ++bx) {
                gatherBlock(rgba, w, h, bx, by, b);
                encodeBlock(b, out.data() + (static_cast<size_t>(by) * bw + bx) * 16);
            }
        }
    };

    // Parallel over block rows. Load-time transcoding is the hot path for
    // texture-heavy scenes (Bistro: hundreds of multi-megapixel textures), so
    // saturate the machine; small images stay single-threaded to skip the
    // thread spawn cost.
    const unsigned hw = std::max(1u, std::thread::hardware_concurrency());
    const int rowsPerThread = 8;
    if (hw > 1 && bh > rowsPerThread * 2) {
        const int nThreads = static_cast<int>(std::min<unsigned>(hw, (bh + rowsPerThread - 1) / rowsPerThread));
        std::vector<std::thread> pool;
        pool.reserve(nThreads);
        const int chunk = (bh + nThreads - 1) / nThreads;
        for (int t = 0; t < nThreads; ++t) {
            const int y0 = t * chunk;
            const int y1 = std::min(bh, y0 + chunk);
            if (y0 >= y1) break;
            pool.emplace_back(encodeRows, y0, y1);
        }
        for (auto& th : pool) th.join();
    } else {
        encodeRows(0, bh);
    }

    return out;
}

std::vector<std::vector<std::uint8_t>> buildMipChainRGBA8(
        const std::uint8_t* rgba, int w, int h, bool srgb) {

    static const SrgbTables kTables;

    std::vector<std::vector<std::uint8_t>> levels;
    const std::uint8_t* src = rgba;// level 0 read straight from the caller
    int cw = w, ch = h;

    while (cw > 1 || ch > 1) {
        const int nw = std::max(1, cw >> 1);
        const int nh = std::max(1, ch >> 1);
        std::vector<std::uint8_t> next(static_cast<size_t>(nw) * nh * 4);

        for (int y = 0; y < nh; ++y) {
            // Odd source dims: the second tap clamps to the last row/col, a
            // plain box on the floor(n/2) grid — adequate for mips.
            const int sy0 = std::min(y * 2, ch - 1);
            const int sy1 = std::min(y * 2 + 1, ch - 1);
            for (int x = 0; x < nw; ++x) {
                const int sx0 = std::min(x * 2, cw - 1);
                const int sx1 = std::min(x * 2 + 1, cw - 1);
                const std::uint8_t* s00 = src + (static_cast<size_t>(sy0) * cw + sx0) * 4;
                const std::uint8_t* s01 = src + (static_cast<size_t>(sy0) * cw + sx1) * 4;
                const std::uint8_t* s10 = src + (static_cast<size_t>(sy1) * cw + sx0) * 4;
                const std::uint8_t* s11 = src + (static_cast<size_t>(sy1) * cw + sx1) * 4;
                std::uint8_t* d = next.data() + (static_cast<size_t>(y) * nw + x) * 4;

                if (srgb) {
                    // RGB in linear space, alpha linearly.
                    for (int c = 0; c < 3; ++c) {
                        const float lin = 0.25f * (kTables.toLinear[s00[c]] + kTables.toLinear[s01[c]] +
                                                   kTables.toLinear[s10[c]] + kTables.toLinear[s11[c]]);
                        const int li = std::clamp(static_cast<int>(lin * 4096.f), 0, 4095);
                        d[c] = kTables.toSrgb[li];
                    }
                    d[3] = static_cast<std::uint8_t>((s00[3] + s01[3] + s10[3] + s11[3] + 2) / 4);
                } else {
                    for (int c = 0; c < 4; ++c) {
                        d[c] = static_cast<std::uint8_t>((s00[c] + s01[c] + s10[c] + s11[c] + 2) / 4);
                    }
                }
            }
        }

        levels.push_back(std::move(next));
        src = levels.back().data();
        cw = nw;
        ch = nh;
    }

    return levels;
}

}// namespace threepp::bcn
