"""
Dear ImGui immediate-mode widgets (call inside ImguiContext.render's draw callback).
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['begin', 'bullet_text', 'button', 'checkbox', 'collapsing_header', 'color_edit3', 'combo', 'drag_float', 'end', 'get_framerate', 'input_float', 'same_line', 'separator', 'set_next_window_pos', 'set_next_window_size', 'show_demo_window', 'slider_float', 'slider_int', 'spacing', 'text', 'tree_node', 'tree_pop']
def begin(name: str) -> bool:
    """
    Start a window; returns False if collapsed. Pair with end().
    """
def bullet_text(text: str) -> None:
    ...
def button(label: str) -> bool:
    """
    Returns True on the frame the button is clicked.
    """
def checkbox(label: str, value: bool) -> tuple[bool, bool]:
    ...
def collapsing_header(label: str) -> bool:
    ...
def color_edit3(label: str, rgb: typing.Annotated[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], "FixedSize(3)"]) -> tuple[bool, tuple[float, float, float]]:
    ...
def combo(label: str, current: typing.SupportsInt | typing.SupportsIndex, items: collections.abc.Sequence[str]) -> tuple[bool, int]:
    ...
def drag_float(label: str, value: typing.SupportsFloat | typing.SupportsIndex, speed: typing.SupportsFloat | typing.SupportsIndex = 1.0, min: typing.SupportsFloat | typing.SupportsIndex = 0.0, max: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> tuple[bool, float]:
    ...
def end() -> None:
    ...
def get_framerate() -> float:
    ...
def input_float(label: str, value: typing.SupportsFloat | typing.SupportsIndex) -> tuple[bool, float]:
    ...
def same_line() -> None:
    ...
def separator() -> None:
    ...
def set_next_window_pos(x: typing.SupportsFloat | typing.SupportsIndex, y: typing.SupportsFloat | typing.SupportsIndex) -> None:
    ...
def set_next_window_size(width: typing.SupportsFloat | typing.SupportsIndex, height: typing.SupportsFloat | typing.SupportsIndex) -> None:
    ...
def show_demo_window() -> None:
    """
    Show the built-in ImGui demo window (a gallery of every widget).
    """
def slider_float(label: str, value: typing.SupportsFloat | typing.SupportsIndex, min: typing.SupportsFloat | typing.SupportsIndex, max: typing.SupportsFloat | typing.SupportsIndex) -> tuple[bool, float]:
    ...
def slider_int(label: str, value: typing.SupportsInt | typing.SupportsIndex, min: typing.SupportsInt | typing.SupportsIndex, max: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, int]:
    ...
def spacing() -> None:
    ...
def text(text: str) -> None:
    ...
def tree_node(label: str) -> bool:
    ...
def tree_pop() -> None:
    ...
