"""The Spot task contract, shared by the play viewers, the trainers and the symmetry mirrors.

Everything here was duplicated across `play_spot_{steps,stairs,heightfield}.py`,
`scratch_distillation/play_spot_flat.py`, `spot_slam.py`, `calico/spot_calico.py` and the three
`train_spot_*.py`. What stays out of here is what genuinely differs per task: `terr_h` (three
terrains — pass yours to `analytic_scan` as `height_fn`), `mirror_obs` (three obs layouts — pass
yours to `make_aux_loss`) and `score_checkpoint` (three success metrics).

Deploy side:  v2_obs, resolve_model, analytic_scan, chase_cam, poll_reload
Trainer side: warmstart_scratch_to_terrain, sanity_walk, stochastic_flat_baseline,
              eval_flat_steering
Mirrors:      symmetry_loss, make_aux_loss (the mirror itself is the caller's)
"""
import math
import os
import sys

import numpy as np
import torch

_HERE = os.path.dirname(os.path.abspath(__file__))                # examples/spot/
sys.path.insert(0, os.path.dirname(os.path.dirname(_HERE)))       # python/  -> threepp
sys.path.insert(0, _HERE)                                         # spot_deploy / spot_terrain_env

import threepp as tp
from threepp.rl import load_policy
from spot_deploy import _quat_to_R, default_q, isaac_to_add
from spot_terrain_env import scan_xy_np

GRAV = np.array([0.0, 0.0, -1.0])


# ── deploy side ───────────────────────────────────────────────────────────────
def v2_obs(art, last_act, cmd, ahead, h_here, phi):
    """96-d SpotStepsEnv obs: [proprio(48)|clock(2)|base_above(1)|scan(45)].
    `ahead` (45) + `h_here` come from EITHER the depth sensor or the oracle.
    `phi` is the current phase scalar ∈ [0,1)."""
    rs, rv = art.root_state(), art.root_velocity()
    R = _quat_to_R(rs[3:7]); Rt = R.T
    lin_b, ang_b, proj_g = Rt @ rv[0:3], Rt @ rv[3:6], Rt @ GRAV
    jp_isaac = art.joint_positions()[isaac_to_add]
    jv_isaac = art.joint_velocities()[isaac_to_add]
    qpos = jp_isaac - default_q
    z = float(rs[2])
    clk = [math.sin(2 * math.pi * phi), math.cos(2 * math.pi * phi)]
    return np.concatenate([lin_b, ang_b, proj_g, cmd, qpos, jv_isaac, last_act,
                           clk, [z - h_here], ahead]).astype(np.float32)


def resolve_model(path):
    """Prefer the exact path, then the gated _best checkpoint, then the always-current
    _latest one. Only _best is tracked in git; _latest and the bare scratch_flat.pt are
    regenerated by train_scratch.py, so a fresh checkout has _best alone."""
    if os.path.exists(path):
        return path
    stem = os.path.splitext(path)[0]
    for suffix in ("_best", "_latest"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    for cand in (stem + "_best.pt", stem + "_latest.pt"):
        if os.path.exists(cand):
            return cand
    return path


def analytic_scan(art, height_fn):
    """Privileged scan: exact terrain height at the 45 heading-relative grid points (the oracle
    baseline). `height_fn(x, y) -> h` is the caller's own numpy terrain mirror."""
    rs = art.root_state(); R = _quat_to_R(rs[3:7])
    x, y = float(rs[0]), float(rs[1])
    hx, hy = float(R[0, 0]), float(R[1, 0]); nrm = math.hypot(hx, hy) or 1.0
    cyaw, syaw = hx / nrm, hy / nrm
    h_here = height_fn(x, y)
    px, py = scan_xy_np(x, y, cyaw, syaw)
    ahead = np.clip(np.array([height_fn(float(pxi), float(pyi)) - h_here
                              for pxi, pyi in zip(px, py)], np.float32), -1.0, 1.0)
    return ahead, h_here


def chase_cam(art, cam, rend, scene, back, height, lag):
    """Sit `back` metres behind Spot's heading at `height`, lerped by `lag` so the pose trails
    as Spot turns, then render."""
    rs = art.root_state(); p = np.array(rs[0:3], float)
    fwd = _quat_to_R(rs[3:7])[:, 0]; fwd = np.array([fwd[0], fwd[1], 0.0])
    nrm = np.linalg.norm(fwd); fwd = fwd / nrm if nrm > 1e-6 else np.array([1.0, 0.0, 0.0])
    desired = p - fwd * back + np.array([0.0, 0.0, height])
    cam.position.lerp(tp.Vector3(float(desired[0]), float(desired[1]), float(desired[2])), lag)
    cam.look_at(float(p[0] + fwd[0] * 0.4), float(p[1] + fwd[1] * 0.4), float(p[2] + 0.1))
    rend.render(scene, cam)


def poll_reload(pol, model, dev, on_reload=None, require_norm=False):
    """Hot-reload watcher: if `model`'s mtime moved, swap the policy in the `pol` dict in place
    and call `on_reload`. Silent on any failure — the trainer is probably mid-write."""
    try:
        mt = os.path.getmtime(model)
        if mt != pol["mt"]:
            ac_new, norm_new, _ = load_policy(model, device=dev)
            if require_norm:
                assert norm_new is not None, "reloaded checkpoint has no RunningNorm"
            pol["ac"], pol["norm"] = ac_new, norm_new
            pol["mt"] = mt
            pol["reloads"] += 1
            if on_reload is not None:
                on_reload()
            print(f"[reload] {os.path.basename(model)} (#{pol['reloads']})")
    except Exception:
        pass


# ── trainer side ──────────────────────────────────────────────────────────────
def warmstart_scratch_to_terrain(ac, norm, scratch_path, n_keep=50, device="cuda"):
    """Transfer the 50-d clock base gait into the 96-d clock+terrain AC.

    Input-layer cols [0:n_keep] copied (proprio+clock), terrain cols zero-init; deeper layers +
    log_std copied verbatim. The obs RunningNorm is expanded: proprio+clock stats kept, terrain
    dims left at the fresh default (mean 0 / var 1), count reset so the norm adapts to the terrain
    distribution during fine-tune (sanity_walk pre-train still sees the loaded proprio stats =
    bit-identical base gait)."""
    src_ac, src_norm, src_meta = load_policy(scratch_path, device=device)
    assert src_meta["obs_dim"] == n_keep, f"expected {n_keep}-d source, got {src_meta['obs_dim']}"
    assert norm is not None and src_norm is not None, "both sides need a RunningNorm"
    with torch.no_grad():
        for dst_net, src_net in ((ac.actor, src_ac.actor), (ac.critic, src_ac.critic)):
            for li in (0, 2, 4, 6):
                dst, src = dst_net[li], src_net[li]
                if li == 0:
                    dst.weight.zero_()
                    dst.weight[:, :n_keep].copy_(src.weight)   # proprio+clock cols; terrain stays 0
                    dst.bias.copy_(src.bias)
                else:
                    dst.weight.copy_(src.weight); dst.bias.copy_(src.bias)
        ac.log_std.copy_(src_ac.log_std)
        norm.mean[:n_keep].copy_(src_norm.mean)
        norm.var[:n_keep].copy_(src_norm.var)
        # leave norm.mean[n_keep:]=0, var[n_keep:]=1 (fresh defaults); keep norm.count fresh (eps)
        # so terrain dims (and proprio under the new distribution) adapt during fine-tune.
    print(f"warm-started clock base gait {os.path.basename(scratch_path)} -> 96-d: cols[:{n_keep}] "
          f"copied, {ac.actor[0].weight.shape[1]-n_keep} terrain cols zero-init; norm expanded")


@torch.no_grad()
def sanity_walk(env, ac, norm, steps=300):
    """Roll the warm-started DETERMINISTIC policy and report tracking. norm-aware: ac.act_mean(norm.norm(obs)).
    Logs both progress metrics: the steps curriculum `level` and the terrain/heightfield `climb`."""
    obs = env.reset()
    for _ in range(steps):
        obs, _, _, _, _ = env.step(ac.act_mean(norm.norm(obs)))
    level = f"{env.last_level:.2f}" if hasattr(env, "last_level") else "n/a"
    climb = env.ep_max_climb.mean().item() if hasattr(env, "ep_max_climb") else "n/a"
    print(f"warm-start sanity ({steps} steps): track={env.last_track:.3f}  flat_track={env.last_flat_track:.3f}  "
          f"level={level}  climb={climb}  fell/step={env.last_fell:.3f}")
    return env.last_flat_track


@torch.no_grad()
def stochastic_flat_baseline(env, ac, norm, steps=240, warm=80):
    """Mean flat-lane tracking under the STOCHASTIC policy (exploration noise).
    Gate baseline calibrated to this — not to the deterministic number — to avoid
    it reading LOW every iter from noise alone."""
    obs = env.reset()
    acc = []
    for t in range(steps):
        obs, _, _, _, _ = env.step(ac.act(norm.norm(obs))[0])
        if t >= warm:
            acc.append(env.last_flat_track)
    return sum(acc) / max(1, len(acc))


@torch.no_grad()
def eval_flat_steering(env_cls, policy_path, k=512, device="cuda", height_source=False, seed=None):
    """Held-out steering regression on FLAT ground vs the scratch base gait (the real steering test).

    `env_cls` is the task's VecTask; `height_source=True` rebuilds it against the height source the
    checkpoint records in its meta; `seed`, when given, pins the command sampler's generator."""
    if not tp.HAS_PHYSX or not torch.cuda.is_available():
        print("need PhysX + CUDA"); return
    ac, norm, meta = load_policy(policy_path, device=device)
    if seed is not None:
        torch.manual_seed(seed)
    kw = {"height_source": meta.get("height_source", "analytic")} if height_source else {}
    env = env_cls(num_envs=k, device=device, flat_only=True, **kw)
    pol = (lambda o: ac.act_mean(norm.norm(o))) if norm is not None else ac.act_mean
    # Base gait teacher (50-d, norm-aware): compare against it so steering regression is defined
    # relative to the actual STARTING point of this fine-tune (not the old Isaac TorchScript).
    base_path = os.path.join(_HERE, "scratch_distillation", "scratch_flat_best.pt")
    base_ac, base_norm, _ = load_policy(base_path, device=device)
    tea = lambda o: base_ac.act_mean(base_norm.norm(o[:, :50]))   # reads the 50-d slice
    grid = [(1.0, 0.0, 0.0), (0.0, 0.0, 0.0), (-0.5, 0.0, 0.0), (0.0, 0.5, 0.0),
            (0.0, -0.5, 0.0), (0.0, 0.0, 1.0), (0.0, 0.0, -1.0), (1.0, 0.0, 0.5)]
    print(f"flat-steering regression ({os.path.basename(policy_path)} vs base gait, K={k}):")
    print("   cmd[vx,vy,wz]      policy_err   teacher_err   ratio")
    worst = 0.0
    for cmd in grid:
        ep = env.measure_tracking(pol, cmd); et = env.measure_tracking(tea, cmd)
        ratio = ep / max(et, 1e-6); worst = max(worst, ratio)
        flag = "" if ratio <= 1.10 else "  <- REGRESSED"
        print(f"   [{cmd[0]:+.1f},{cmd[1]:+.1f},{cmd[2]:+.1f}]     {ep:8.3f}    {et:8.3f}    {ratio:5.2f}{flag}")
    print(f"worst ratio {worst:.2f}  ->  {'PASS (steering preserved)' if worst <= 1.10 else 'FAIL (steering degraded)'}")


# ── symmetry augmentation ─────────────────────────────────────────────────────
def symmetry_loss(ac, obs, mirror_obs, mirror_act):
    """Equivariance penalty: actor(mirror(obs)) should equal mirror(actor(obs)). Mean-squared over the
    action. Drives the policy toward a symmetric gait (kills the rightward drift + strafe asymmetry).
    The mirror pair is the caller's — each obs layout has its own."""
    feat = ac._feat(obs)
    mean = ac.actor(feat)
    mean_m = ac.actor(ac._feat(mirror_obs(obs)))
    return (mean_m - mirror_act(mean)).pow(2).mean()


def make_aux_loss(coef, mirror_obs, mirror_act):
    """Build an aux_loss(ac, obs) -> scalar for PPO. coef weights the symmetry penalty; it is called
    on PPO's already-normalized obs, so the mirror's scale-invariance is satisfied."""
    return lambda ac, obs: coef * symmetry_loss(ac, obs, mirror_obs, mirror_act)
