# cmake/EmbedWgslFile.cmake
# CMake -P script: combines two naga-generated WGSL files into C++ source/header.
#
# Expected input variables (passed via -D):
#   VERT_WGSL    - path to the vertex .wgsl file
#   FRAG_WGSL    - path to the fragment .wgsl file
#   OUT_HPP      - output header path
#   OUT_CPP      - output source path
#   SHADER_NAME  - human-readable shader name (used for C identifier)

if(NOT DEFINED VERT_WGSL OR NOT DEFINED FRAG_WGSL OR
   NOT DEFINED OUT_HPP OR NOT DEFINED OUT_CPP OR NOT DEFINED SHADER_NAME)
    message(FATAL_ERROR
        "EmbedWgslFile.cmake requires: VERT_WGSL, FRAG_WGSL, OUT_HPP, OUT_CPP, SHADER_NAME")
endif()

# Read the WGSL sources produced by naga
file(READ "${VERT_WGSL}" vert_wgsl_text)
file(READ "${FRAG_WGSL}" frag_wgsl_text)

# Rename entry points to vs_main / fs_main.
# naga typically generates:
#   @vertex fn main(...) for vertex shaders
#   @fragment fn main(...) for fragment shaders
# We need them to be vs_main and fs_main so both can coexist or be referenced
# by the pipeline descriptor.

# Handle multi-line: @vertex\nfn main(
string(REGEX REPLACE "@vertex[ \t]*\r?\nfn ([a-zA-Z_][a-zA-Z0-9_]*)" "@vertex\nfn vs_main" vert_wgsl_text "${vert_wgsl_text}")
# Handle single-line: @vertex fn main(
string(REGEX REPLACE "@vertex[ \t]+fn ([a-zA-Z_][a-zA-Z0-9_]*)" "@vertex fn vs_main" vert_wgsl_text "${vert_wgsl_text}")

# Same for fragment
string(REGEX REPLACE "@fragment[ \t]*\r?\nfn ([a-zA-Z_][a-zA-Z0-9_]*)" "@fragment\nfn fs_main" frag_wgsl_text "${frag_wgsl_text}")
string(REGEX REPLACE "@fragment[ \t]+fn ([a-zA-Z_][a-zA-Z0-9_]*)" "@fragment fn fs_main" frag_wgsl_text "${frag_wgsl_text}")

# Build C identifier from shader name
string(MAKE_C_IDENTIFIER "${SHADER_NAME}" ident)

# Generate header
set(hpp_content "\
// Auto-generated by EmbedWgslFile.cmake -- do not edit.
#ifndef THREEPP_WGSL_${ident}_HPP
#define THREEPP_WGSL_${ident}_HPP

namespace threepp::wgpu::wgsl {
    extern const char* ${ident}_vert;
    extern const char* ${ident}_frag;
}

#endif // THREEPP_WGSL_${ident}_HPP
")

# Generate source with raw string literals using a custom delimiter to avoid
# collisions with WGSL content.
set(cpp_content "\
// Auto-generated by EmbedWgslFile.cmake -- do not edit.
#include \"threepp/renderers/wgpu/wgsl/${ident}_wgsl.hpp\"

namespace threepp::wgpu::wgsl {

const char* ${ident}_vert = R\"THREEPP_WGSL(${vert_wgsl_text})THREEPP_WGSL\";

const char* ${ident}_frag = R\"THREEPP_WGSL(${frag_wgsl_text})THREEPP_WGSL\";

} // namespace threepp::wgpu::wgsl
")

file(WRITE "${OUT_HPP}" "${hpp_content}")
file(WRITE "${OUT_CPP}" "${cpp_content}")
