# cmake/EmbedWgslPathTracerScript.cmake
# Worker script run as `cmake -P` by EmbedWgslPathTracer.cmake. Reads each
# .wgsl file under WGSL_DIR and emits OUT_CPP — a single C++ source file
# defining the fragment globals as chunked raw string literals.
#
# Inputs (passed via -D):
#   WGSL_DIR  - directory containing the .wgsl files
#   OUT_CPP   - path to write the generated .cpp file
#
# To add or rename a fragment, edit the SHADER_PAIRS list below AND the
# build functions in src/threepp/renderers/wgpu/pathtracer/WgpuPathTracerShaders.cpp.

if(NOT DEFINED WGSL_DIR OR NOT DEFINED OUT_CPP)
    message(FATAL_ERROR "EmbedWgslPathTracerScript.cmake: WGSL_DIR and OUT_CPP are required")
endif()

# (.wgsl basename, C++ symbol) pairs. Order matches the original source layout
# but is otherwise arbitrary; build functions concatenate by symbol name.
set(SHADER_PAIRS
    "pt_shared_defs"     "csSharedDefsWGSL"
    "pt_common"          "csCommonWGSL"
    "pt_pathtrace"       "csPathTraceWGSL"
    "pt_run_bounces1"    "csRunBouncesWGSL1"
    "pt_run_bounces2"    "csRunBouncesWGSL2"
    "pt_primary_shade1"  "csPrimaryShadeWGSL1"
    "pt_primary_shade2"  "csPrimaryShadeWGSL2"
    "pt_primary_shade3"  "csPrimaryShadeWGSL3"
    "pt_pathtrace2"      "csPathTraceWGSL2"
    "pt_pathtrace3"      "csPathTraceWGSL3"
    "pt_bounce1"         "csBounce1WGSL"
    "pt_accum1"          "csAccumWGSL1"
    "pt_vt"              "vtWGSL_"
    "pt_refit"           "refitWGSL_"
    "pt_svgf_atrous"     "svgfAtrousWGSL"
    "pt_depth_fill"      "depthFillWGSL"
    "pt_display"         "displayWGSL"
    "pt_upscale"         "upscaleWGSL"
)

# Conservative cap — well under MSVC's per-string-literal limits. Adjacent
# raw string literals are concatenated by the C++ compiler.
set(CHUNK_SIZE 8000)

set(content "")
string(APPEND content "// Auto-generated by cmake/EmbedWgslPathTracer.cmake -- do not edit.\n")
string(APPEND content "// Source files: src/threepp/renderers/wgpu/pathtracer/shaders/*.wgsl\n\n")
string(APPEND content "#include \"threepp/renderers/wgpu/pathtracer/WgpuPathTracerShaders.hpp\"\n\n")
string(APPEND content "namespace threepp::wgpu_pt {\n\n")

list(LENGTH SHADER_PAIRS _n)
math(EXPR _last "${_n} - 1")
foreach(_i RANGE 0 ${_last} 2)
    list(GET SHADER_PAIRS ${_i} basename)
    math(EXPR _j "${_i} + 1")
    list(GET SHADER_PAIRS ${_j} symbol)

    set(wgsl_file "${WGSL_DIR}/${basename}.wgsl")
    if(NOT EXISTS "${wgsl_file}")
        message(FATAL_ERROR "EmbedWgslPathTracerScript: missing ${wgsl_file}")
    endif()
    file(READ "${wgsl_file}" body)

    string(APPEND content "// ${basename}.wgsl\n")
    # Explicit `extern` is required: const at namespace scope has internal
    # linkage in C++ by default, which would hide these symbols from the
    # build-function TU in WgpuPathTracerShaders.cpp.
    string(APPEND content "extern const char* const ${symbol} =\n")

    string(LENGTH "${body}" _blen)
    if(_blen EQUAL 0)
        string(APPEND content "    \"\"\n")
    else()
        set(_pos 0)
        while(_pos LESS _blen)
            math(EXPR _rem "${_blen} - ${_pos}")
            if(_rem LESS ${CHUNK_SIZE})
                set(_csize ${_rem})
            else()
                set(_csize ${CHUNK_SIZE})
            endif()
            string(SUBSTRING "${body}" ${_pos} ${_csize} _chunk)
            string(APPEND content "    R\"PTWGSL(${_chunk})PTWGSL\"\n")
            math(EXPR _pos "${_pos} + ${_csize}")
        endwhile()
    endif()
    string(APPEND content ";\n\n")
endforeach()

string(APPEND content "}// namespace threepp::wgpu_pt\n")

file(WRITE "${OUT_CPP}" "${content}")
